### ISSUE TITLE
Possible incompatibility with python 2.7

### ISSUE THREAD

**Issue by adamwight** [halfak/Deltas#5]
I get the following error,

> import deltas.tokenizers

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/deltas/__init__.py", line 3, in <module>
    from .algorithms.diff_engine import DiffEngine
  File "/usr/local/lib/python2.7/dist-packages/deltas/algorithms/__init__.py", line 18, in <module>
    from .segment_matcher import SegmentMatcher
  File "/usr/local/lib/python2.7/dist-packages/deltas/algorithms/segment_matcher.py", line 20, in <module>
    from . import sequence_matcher
  File "/usr/local/lib/python2.7/dist-packages/deltas/algorithms/sequence_matcher.py", line 10, in <module>
    from ..tokenizers import text_split
  File "/usr/local/lib/python2.7/dist-packages/deltas/tokenizers/__init__.py", line 16, in <module>
    from .tokenizer import Tokenizer, RegexTokenizer
  File "/usr/local/lib/python2.7/dist-packages/deltas/tokenizers/tokenizer.py", line 6, in <module>
    from .token import Token
  File "/usr/local/lib/python2.7/dist-packages/deltas/tokenizers/token.py", line 8, in <module>
    class Token(str):
TypeError: Error when calling the metaclass bases
    nonempty __slots__ not supported for subtype of 'str'
```

**Comment by adamwight** [comment]
Fossilized discussion: https://mail.python.org/pipermail/patches/2003-July/013062.html
